### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by fbusta** [paypal/TLS-update#19]
Hi guys, since yesterday noon we are getting this error when consuming one of your REST APIs. Have you guys done anything that could affect the connection? (new certs or similar). The infrastructure of our service hasn't changed and we did consume your endpoint before without any problem.

**Comment by bluk** [comment]
I'm not aware of any changes and haven't seen any similar reports.

Can you please elaborate on your environment? I'm assuming you're using .NET since the title of the issue corresponds to a common .NET error. Specifically can you give the .NET version and whether you're trying to connect to PayPal or Braintree? Also if it's sandbox or production.

**Comment by fbusta** [comment]
Thanks @bluk. We are consuming this endpoint: https://api-3t.paypal.com/nvp from a .NET app. We're using framework 4.6 and before yesterday everything worked fine. We didn't enforce TLS 1.2 (which is what .NET framework 4.6 uses by default) however we are doing that change now. This is production systems. Have paypal done any update in how it handles secure connections ?? Thanks for the response!

**Comment by bluk** [comment]
There should not have been any major PayPal infrastructure changes in the last couple days. TLS 1.2 isn't required yet for production (only sandbox) so I'm not sure that would change anything. The final change to SHA256 signed certificates was made over a month ago so not too sure that would be it either.

Since this is a live production issue, you should contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) who can assist you.

**Comment by fbusta** [comment]
ok, thanks for the info. Yeah it's pretty weird what's happening. I'll open a ticket with tech support
